/-
Copyright (c) 2026 Aalok Thakkar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aalok Thakkar
-/

import DiagonaLean.EmpCFG.Basic
import DiagonaLean.PCP.Basic

@[expose] public section

/-! # PCP ⪯ₘ EmpCFG

Reduction from PCP to EmpCFG following the Hopcroft–Ullman construction. Strings in the intersection
of `topCFG P` and `botCFG P` encode valid solution tile sequences for the PCP instance `P`. The main
results are `pcp_iff_nempcfg` and `npcp_iff_empcfg`.

## References

* [J. E. Hopcroft, R. Motwani, J. D. Ullman,
  *Introduction to Automata Theory, Languages, and Computation*][HopcroftMotwaniUllman2006]
-/

namespace EmpCFG.Reduction

open DiagonaLean.EmpCFG DiagonaLean.PCP ContextFreeGrammar

variable {α : Type} [DecidableEq α]

/-- The terminal alphabet of the reduced CFG-intersection instance: PCP symbols on the `.inl` side,
  tile markers on the `.inr` side. -/
abbrev Term (α : Type) := α ⊕ Tile α

/-- Concatenate `proj t` for each tile in the stack. Specialises to `τ1` (with `proj = Tile.top`)
  and `τ2` (with `proj = Tile.bot`). -/
def τProj (proj : Tile α → Word α) : Stack α → Word α
  | []      => []
  | t :: A  => proj t ++ τProj proj A

omit [DecidableEq α] in
/-- `τProj proj` of the empty stack is empty. -/
@[simp]
lemma τProj_nil (proj : Tile α → Word α) :
    τProj proj ([] : Stack α) = [] := rfl

omit [DecidableEq α] in
/-- `τProj proj` of a cons stack prepends `proj t`. -/
@[simp]
lemma τProj_cons (proj : Tile α → Word α) (t : Tile α) (A : Stack α) :
    τProj proj (t :: A) = proj t ++ τProj proj A := rfl

omit [DecidableEq α] in
/-- `τProj proj` distributes over stack concatenation. -/
@[simp]
lemma τProj_append (proj : Tile α → Word α) (A B : Stack α) :
    τProj proj (A ++ B) = τProj proj A ++ τProj proj B := by
  induction A with
  | nil => simp
  | cons t A ih => simp [ih, List.append_assoc]

omit [DecidableEq α] in
/-- `τProj Tile.top` equals `τ1`. -/
@[simp]
lemma τProj_top (A : Stack α) : τProj Tile.top A = τ1 A := by
  induction A with
  | nil => rfl
  | cons t A ih => simp [τ1, ih]

omit [DecidableEq α] in
/-- `τProj Tile.bot` equals `τ2`. -/
@[simp]
lemma τProj_bot (A : Stack α) : τProj Tile.bot A = τ2 A := by
  induction A with
  | nil => rfl
  | cons t A ih => simp [τ2, ih]

/-- The recursive rule generated by a tile `t`: `S → (proj t).inl ++ [S] ++ [.inr t]`. -/
def recRule (proj : Tile α → Word α) (t : Tile α) :
    ContextFreeRule (Term α) Unit :=
  ⟨(),
    (proj t).map (fun a => Symbol.terminal (Sum.inl a))
      ++ [Symbol.nonterminal ()]
      ++ [Symbol.terminal (Sum.inr t)]⟩

/-- The base rule generated by a tile `t`: `S → (proj t).inl ++ [.inr t]`. -/
def baseRule (proj : Tile α → Word α) (t : Tile α) :
    ContextFreeRule (Term α) Unit :=
  ⟨(),
    (proj t).map (fun a => Symbol.terminal (Sum.inl a))
      ++ [Symbol.terminal (Sum.inr t)]⟩

/-- The grammar `genCFG proj P`: single nonterminal `()`, rules `recRule proj t` and
  `baseRule proj t` for each `t ∈ P`. -/
def genCFG (proj : Tile α → Word α) (P : Stack α) :
    ContextFreeGrammar (Term α) where
  NT := Unit
  initial := ()
  rules := P.toFinset.image (recRule proj) ∪ P.toFinset.image (baseRule proj)

/-- The "top" grammar: emits `t.top` for each tile. -/
abbrev topCFG (P : Stack α) : ContextFreeGrammar (Term α) := genCFG Tile.top P

/-- The "bot" grammar: emits `t.bot` for each tile. -/
abbrev botCFG (P : Stack α) : ContextFreeGrammar (Term α) := genCFG Tile.bot P

/-- A rule belongs to `(genCFG proj P).rules` iff it is `recRule proj t` or `baseRule proj t` for
  some `t ∈ P`. -/
lemma mem_rules_iff (proj : Tile α → Word α) (P : Stack α)
    (r : ContextFreeRule (Term α) Unit) :
    r ∈ (genCFG proj P).rules ↔
      ∃ t ∈ P, r = recRule proj t ∨ r = baseRule proj t := by
  unfold genCFG
  simp only [Finset.mem_union, Finset.mem_image, List.mem_toFinset]
  constructor
  · rintro (⟨t, ht, rfl⟩ | ⟨t, ht, rfl⟩)
    · exact ⟨t, ht, Or.inl rfl⟩
    · exact ⟨t, ht, Or.inr rfl⟩
  · rintro ⟨t, ht, rfl | rfl⟩
    · exact Or.inl ⟨t, ht, rfl⟩
    · exact Or.inr ⟨t, ht, rfl⟩

/-- The canonical string the grammar produces from a stack `A`: `α`-side concatenation of `proj`
  followed by reversed tile markers. -/
def canonString (proj : Tile α → Word α) (A : Stack α) : List (Term α) :=
  (τProj proj A).map Sum.inl ++ A.reverse.map Sum.inr

omit [DecidableEq α] in
/-- `canonString proj` of the empty stack is empty. -/
@[simp]
lemma canonString_nil (proj : Tile α → Word α) :
    canonString proj ([] : Stack α) = [] := by
  simp [canonString]

omit [DecidableEq α] in
/-- `canonString proj` of a cons stack prepends `(proj t).inl` and appends `[Sum.inr t]`. -/
@[simp]
lemma canonString_cons (proj : Tile α → Word α)
    (t : Tile α) (A : Stack α) :
    canonString proj (t :: A) =
      (proj t).map Sum.inl ++ canonString proj A ++ [Sum.inr t] := by
  simp [canonString, List.map_append, List.append_assoc]

/-- Lift an α-word to a list of `Symbol`s, using `Sum.inl` then `terminal`. -/
abbrev embedA (w : Word α) : List (Symbol (Term α) Unit) :=
  w.map (fun a => Symbol.terminal (Sum.inl a))

/-- Lift a stack to a list of `Symbol`s, using `Sum.inr` then `terminal`. -/
abbrev embedT (A : Stack α) : List (Symbol (Term α) Unit) :=
  A.map (fun t => Symbol.terminal (Sum.inr t))

omit [DecidableEq α] in
/-- `embedA` distributes over word concatenation. -/
lemma embedA_append (w₁ w₂ : Word α) :
    embedA (w₁ ++ w₂) = embedA w₁ ++ embedA w₂ := by simp [embedA]

omit [DecidableEq α] in
/-- `embedT` distributes over stack concatenation. -/
lemma embedT_append (A B : Stack α) :
    embedT (A ++ B) = embedT A ++ embedT B := by simp [embedT]

omit [DecidableEq α] in
/-- `embedA` of the empty word is empty. -/
@[simp]
lemma embedA_nil : embedA ([] : Word α) = [] := rfl

omit [DecidableEq α] in
/-- `embedT` of the empty stack is empty. -/
@[simp]
lemma embedT_nil : embedT ([] : Stack α) = [] := rfl

omit [DecidableEq α] in
/-- `embedT` of a singleton stack is the single terminal symbol. -/
@[simp]
lemma embedT_singleton (t : Tile α) :
    embedT [t] = [Symbol.terminal (Sum.inr t)] := rfl

omit [DecidableEq α] in
/-- `(canonString proj A).map Symbol.terminal` equals
  `embedA (τProj proj A) ++ embedT A.reverse`. -/
lemma canonString_map_terminal (proj : Tile α → Word α) (A : Stack α) :
    (canonString proj A).map Symbol.terminal =
      embedA (τProj proj A) ++ embedT A.reverse := by
  simp [canonString, embedA, embedT, List.map_map, Function.comp_def]

omit [DecidableEq α] in
/-- `Rewrites.input_output` packaged for `recRule`. -/
private lemma recRule_rewrites (proj : Tile α → Word α) (t : Tile α) :
    (recRule proj t).Rewrites [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.nonterminal ()] ++ [Symbol.terminal (Sum.inr t)]) :=
  ContextFreeRule.Rewrites.input_output

omit [DecidableEq α] in
/-- `Rewrites.input_output` packaged for `baseRule`. -/
private lemma baseRule_rewrites (proj : Tile α → Word α) (t : Tile α) :
    (baseRule proj t).Rewrites [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)]) :=
  ContextFreeRule.Rewrites.input_output

/-- From `[S]`, the grammar derives the "intermediate" form
  `embedA (τProj proj A) ++ [S] ++ embedT A.reverse` for any `A` whose tiles are all in `P`. -/
private lemma derives_intermediate (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_mem : ∀ t ∈ A, t ∈ P) :
    (genCFG proj P).Derives [Symbol.nonterminal ()]
      (embedA (τProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse) := by
  induction A with
  | nil =>
    simp only [τProj_nil, embedA_nil, List.reverse_nil, embedT_nil, List.nil_append]
    exact Relation.ReflTransGen.refl
  | cons t A' ih =>
    have ht : t ∈ P := h_mem t (List.mem_cons_self ..)
    have h_mem' : ∀ t' ∈ A', t' ∈ P := fun t' ht' =>
      h_mem t' (List.mem_cons_of_mem _ ht')
    have h_rule : recRule proj t ∈ (genCFG proj P).rules := by
      rw [mem_rules_iff]; exact ⟨t, ht, Or.inl rfl⟩
    have step1 : (genCFG proj P).Produces [Symbol.nonterminal ()]
        (embedA (proj t) ++ [Symbol.nonterminal ()] ++ [Symbol.terminal (Sum.inr t)]) :=
      ⟨recRule proj t, h_rule, recRule_rewrites proj t⟩
    have step2 := ((ih h_mem').append_left (embedA (proj t))).append_right
      [Symbol.terminal (Sum.inr t)]
    have step3 := step1.single.trans step2
    have h_eq :
        embedA (proj t)
          ++ (embedA (τProj proj A') ++ [Symbol.nonterminal ()] ++ embedT A'.reverse)
          ++ [Symbol.terminal (Sum.inr t)] =
        embedA (τProj proj (t :: A')) ++ [Symbol.nonterminal ()]
            ++ embedT (t :: A').reverse := by
      simp only [τProj_cons, List.reverse_cons, embedA_append, embedT_append,
                 embedT_singleton, List.append_assoc]
    exact h_eq ▸ step3

/-- The grammar derives `(canonString proj A).map Symbol.terminal` from `[S]` for any non-empty `A`
  with tiles in `P`. -/
private lemma derives_canonString_map (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_ne : A ≠ []) (h_mem : ∀ t ∈ A, t ∈ P) :
    (genCFG proj P).Derives [Symbol.nonterminal ()]
      ((canonString proj A).map Symbol.terminal) := by
  obtain ⟨A', t, rfl⟩ : ∃ (A' : Stack α) (t : Tile α), A = A' ++ [t] :=
    ⟨A.dropLast, A.getLast h_ne, (List.dropLast_append_getLast h_ne).symm⟩
  have ht : t ∈ P := h_mem t (by simp)
  have h_mem' : ∀ t' ∈ A', t' ∈ P := fun t' ht' =>
    h_mem t' (List.mem_append.mpr (Or.inl ht'))
  have h_inter := derives_intermediate proj P A' h_mem'
  have h_rule : baseRule proj t ∈ (genCFG proj P).rules := by
    rw [mem_rules_iff]; exact ⟨t, ht, Or.inr rfl⟩
  have step_base : (genCFG proj P).Produces [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)]) :=
    ⟨baseRule proj t, h_rule, baseRule_rewrites proj t⟩
  have step_base_in_context :=
    (step_base.append_left (embedA (τProj proj A'))).append_right (embedT A'.reverse)
  have main_derives := h_inter.trans step_base_in_context.single
  have h_eq :
      embedA (τProj proj A')
        ++ (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)])
        ++ embedT A'.reverse =
      (canonString proj (A' ++ [t])).map Symbol.terminal := by
    simp only [canonString, τProj_append, τProj_cons, τProj_nil, List.append_nil,
               List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
               embedA, embedT, List.map_append, List.map_cons, List.map_nil,
               List.map_map, Function.comp_def, List.append_assoc]
  exact h_eq ▸ main_derives

/-- For any non-empty stack `A` with tiles in `P`, the grammar `genCFG proj P` generates the
  canonical string. -/
lemma genCFG_generates_canonString (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_ne : A ≠ []) (h_mem : ∀ t ∈ A, t ∈ P) :
    (canonString proj A) ∈ (genCFG proj P).language :=
  derives_canonString_map proj P A h_ne h_mem

omit [DecidableEq α] in
/-- No `.nonterminal` symbol occurs in `embedA w`. -/
private lemma not_nonterminal_in_embedA (w : Word α) (n : Unit) :
    Symbol.nonterminal n ∉ embedA w := by
  intro h
  obtain ⟨a, _, ha⟩ := List.mem_map.mp h
  cases ha

omit [DecidableEq α] in
/-- No `.nonterminal` symbol occurs in `embedT A`. -/
private lemma not_nonterminal_in_embedT (A : Stack α) (n : Unit) :
    Symbol.nonterminal n ∉ embedT A := by
  intro h
  obtain ⟨t, _, ht⟩ := List.mem_map.mp h
  cases ht

/-- Splitting at a unique element: if `xs ++ [a] ++ ys = us ++ [a] ++ vs` and `a ∉ xs` and `a ∉ ys`,
  then `xs = us` and `ys = vs`. -/
private lemma split_at_unique {β : Type} {a : β} {xs ys us vs : List β}
    (h_xs : a ∉ xs) (h_ys : a ∉ ys)
    (heq : xs ++ [a] ++ ys = us ++ [a] ++ vs) :
    xs = us ∧ ys = vs := by
  induction xs generalizing us with
  | nil =>
    cases us with
    | nil => simpa using heq
    | cons u us' =>
      exfalso
      simp only [List.nil_append, List.cons_append, List.cons.injEq] at heq
      obtain ⟨_, h_ys_eq⟩ := heq
      apply h_ys
      rw [h_ys_eq]
      simp
  | cons x xs' ih =>
    cases us with
    | nil =>
      exfalso
      simp only [List.nil_append, List.cons_append, List.cons.injEq] at heq
      apply h_xs
      rw [heq.1]
      simp
    | cons u us' =>
      simp only [List.cons_append, List.cons.injEq] at heq
      obtain ⟨h_xu, hrest⟩ := heq
      have h_xs' : a ∉ xs' := fun h => h_xs (List.mem_cons_of_mem _ h)
      obtain ⟨h_xs_eq, h_ys_eq⟩ := ih h_xs' hrest
      exact ⟨by rw [h_xu, h_xs_eq], h_ys_eq⟩

/-- The two-form invariant describing strings reachable from `[S]`. We use a disjunction rather than
  an inductive type to make case analysis amenable to `rcases` (which handles disjunctions cleanly
  even when the indices are non-trivial). -/
private def Form (proj : Tile α → Word α) (P : Stack α)
    (s : List (Symbol (Term α) Unit)) : Prop :=
  (∃ A : Stack α, (∀ t ∈ A, t ∈ P) ∧
    s = embedA (τProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse) ∨
  (∃ A : Stack α, A ≠ [] ∧ (∀ t ∈ A, t ∈ P) ∧
    s = embedA (τProj proj A) ++ embedT A.reverse)

omit [DecidableEq α] in
/-- `[S]` satisfies `Form` with the empty stack. -/
private lemma form_init (proj : Tile α → Word α) (P : Stack α) :
    Form proj P [Symbol.nonterminal ()] := by
  refine Or.inl ⟨[], by simp, ?_⟩; simp

/-- The invariant `Form` is preserved by a single `Produces` step. -/
private lemma form_step (proj : Tile α → Word α) (P : Stack α)
    {s s' : List (Symbol (Term α) Unit)}
    (h_form : Form proj P s) (h_step : (genCFG proj P).Produces s s') :
    Form proj P s' := by
  obtain ⟨r, h_r, h_rw⟩ := h_step
  have h_r' : ∃ t ∈ P, r = recRule proj t ∨ r = baseRule proj t := by
    have hmem : r ∈ ((genCFG proj P).rules : Set _) := Finset.mem_coe.mpr h_r
    unfold genCFG at hmem
    simp only [Finset.coe_union, Finset.coe_image, List.coe_toFinset] at hmem
    rcases hmem with ⟨t, ht, rfl⟩ | ⟨t, ht, rfl⟩
    · exact ⟨t, ht, Or.inl rfl⟩
    · exact ⟨t, ht, Or.inr rfl⟩
  obtain ⟨t, ht, h_t_rule⟩ := h_r'
  rcases h_form with ⟨A, h_mem, h_s_form⟩ | ⟨A, h_ne, h_mem, h_s_form⟩
  · obtain ⟨p, q, h_eq_s, h_eq_s'⟩ := h_rw.exists_parts
    rcases h_t_rule with rfl | rfl
    · rw [h_s_form] at h_eq_s
      have h_eq_s_norm :
          embedA (τProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse
            = p ++ [Symbol.nonterminal ()] ++ q := h_eq_s
      obtain ⟨h_p_eq, h_q_eq⟩ : embedA (τProj proj A) = p ∧ embedT A.reverse = q :=
        split_at_unique (not_nonterminal_in_embedA _ _) (not_nonterminal_in_embedT _ _)
          h_eq_s_norm
      subst h_p_eq; subst h_q_eq
      have h_mem_new : ∀ t' ∈ A ++ [t], t' ∈ P := by
        intros t' ht'
        rcases List.mem_append.mp ht' with h | h
        · exact h_mem t' h
        · simp at h; rw [h]; exact ht
      have h_form_new :
          embedA (τProj proj (A ++ [t])) ++ [Symbol.nonterminal ()]
            ++ embedT (A ++ [t]).reverse =
          embedA (τProj proj A) ++ (recRule proj t).output ++ embedT A.reverse := by
        simp only [recRule, τProj_append, τProj_cons, τProj_nil, List.append_nil,
                   List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
                   embedA, embedT, List.map_append, List.map_cons, List.map_nil,
                   List.append_assoc]
      refine Or.inl ⟨A ++ [t], h_mem_new, ?_⟩
      rw [h_eq_s']; exact h_form_new.symm
    · rw [h_s_form] at h_eq_s
      have h_eq_s_norm :
          embedA (τProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse
            = p ++ [Symbol.nonterminal ()] ++ q := h_eq_s
      obtain ⟨h_p_eq, h_q_eq⟩ : embedA (τProj proj A) = p ∧ embedT A.reverse = q :=
        split_at_unique (not_nonterminal_in_embedA _ _) (not_nonterminal_in_embedT _ _)
          h_eq_s_norm
      subst h_p_eq; subst h_q_eq
      have h_mem_new : ∀ t' ∈ A ++ [t], t' ∈ P := by
        intros t' ht'
        rcases List.mem_append.mp ht' with h | h
        · exact h_mem t' h
        · simp at h; rw [h]; exact ht
      have h_ne_new : A ++ [t] ≠ [] := by simp
      have h_form_new :
          embedA (τProj proj (A ++ [t])) ++ embedT (A ++ [t]).reverse =
          embedA (τProj proj A) ++ (baseRule proj t).output ++ embedT A.reverse := by
        simp only [baseRule, τProj_append, τProj_cons, τProj_nil, List.append_nil,
                   List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
                   embedA, embedT, List.map_append, List.map_cons, List.map_nil,
                   List.append_assoc]
      refine Or.inr ⟨A ++ [t], h_ne_new, h_mem_new, ?_⟩
      rw [h_eq_s']; exact h_form_new.symm
  · exfalso
    have h_n_mem : Symbol.nonterminal r.input ∈ s := h_rw.nonterminal_input_mem
    rw [h_s_form] at h_n_mem
    rcases List.mem_append.mp h_n_mem with h1 | h2
    · exact not_nonterminal_in_embedA _ _ h1
    · exact not_nonterminal_in_embedT _ _ h2

/-- The invariant `Form` is preserved by any number of `Produces` steps. -/
private lemma form_preserved (proj : Tile α → Word α) (P : Stack α)
    {s s' : List (Symbol (Term α) Unit)} (h_derives : (genCFG proj P).Derives s s')
    (h_init : Form proj P s) : Form proj P s' := by
  induction h_derives with
  | refl => exact h_init
  | tail _ h_step h_ih => exact form_step proj P h_ih h_step

/-- Any string reachable from `[S]` in the grammar satisfies `Form`. -/
private lemma form_holds (proj : Tile α → Word α) (P : Stack α)
    {s : List (Symbol (Term α) Unit)}
    (h_derives : (genCFG proj P).Derives [Symbol.nonterminal ()] s) :
    Form proj P s :=
  form_preserved proj P h_derives (form_init proj P)

/-- A word `w` is in `(genCFG proj P).language` iff it is
  `canonString proj A` for some non-empty stack `A` with tiles in `P`. -/
lemma mem_language_iff_canonString (proj : Tile α → Word α) (P : Stack α)
    (w : List (Term α)) :
    w ∈ (genCFG proj P).language ↔
    ∃ A : Stack α, A ≠ [] ∧ (∀ t ∈ A, t ∈ P) ∧ w = canonString proj A := by
  constructor
  · intro h_mem
    rw [mem_language_iff] at h_mem
    have h_form : Form proj P (w.map Symbol.terminal) := form_holds proj P h_mem
    rcases h_form with ⟨A, _, h_eq⟩ | ⟨A, h_ne, h_mem_A, h_eq⟩
    · exfalso
      have h_n : Symbol.nonterminal () ∈ w.map (Symbol.terminal : Term α → _) := by
        rw [h_eq]; simp
      obtain ⟨a, _, ha⟩ := List.mem_map.mp h_n
      cases ha
    · refine ⟨A, h_ne, h_mem_A, ?_⟩
      have h_term_inj :
          Function.Injective (Symbol.terminal : Term α → Symbol (Term α) Unit) :=
        fun _ _ h => Symbol.terminal.inj h
      have h_map_inj :
          Function.Injective (List.map (Symbol.terminal : Term α → Symbol (Term α) Unit)) :=
        List.map_injective_iff.mpr h_term_inj
      apply h_map_inj
      show (w.map Symbol.terminal : List (Symbol (Term α) Unit))
            = (canonString proj A).map Symbol.terminal
      rw [h_eq]
      simp only [canonString, embedA, embedT, List.map_append, List.map_map,
                 Function.comp_def]
  · rintro ⟨A, h_ne, h_mem, rfl⟩
    exact genCFG_generates_canonString proj P A h_ne h_mem

/-- A list of the form `xs.map Sum.inl ++ ys.map Sum.inr` is uniquely decomposable: the `inl` prefix
  and `inr` suffix are determined by the list. -/
private lemma list_inl_inr_split {β γ : Type} :
    ∀ (xs xs' : List β) (ys ys' : List γ),
    xs.map Sum.inl ++ ys.map Sum.inr = xs'.map Sum.inl ++ ys'.map Sum.inr →
    xs = xs' ∧ ys = ys' := by
  intro xs xs' ys ys' h
  induction xs generalizing xs' with
  | nil =>
    cases xs' with
    | nil =>
      simp only [List.nil_append, List.map_nil] at h
      refine ⟨rfl, ?_⟩
      have h_inr_inj : Function.Injective (Sum.inr : γ → β ⊕ γ) :=
        fun _ _ => Sum.inr.inj
      exact (List.map_injective_iff.mpr h_inr_inj) h
    | cons x' xs'' =>
      exfalso
      simp only [List.nil_append, List.map_nil, List.map_cons, List.cons_append] at h
      cases ys with
      | nil => simp at h
      | cons y ys'' =>
        simp only [List.map_cons, List.cons.injEq] at h
        exact absurd h.1 (fun he => by injection he)
  | cons x xs'' ih =>
    cases xs' with
    | nil =>
      exfalso
      simp only [List.nil_append, List.map_nil, List.map_cons, List.cons_append] at h
      cases ys' with
      | nil => simp at h
      | cons y' ys''' =>
        simp only [List.map_cons, List.cons.injEq] at h
        exact absurd h.1 (fun he => by injection he)
    | cons x' xs''' =>
      simp only [List.map_cons, List.cons_append, List.cons.injEq] at h
      obtain ⟨h_head, h_rest⟩ := h
      have h_x_eq : x = x' := Sum.inl.inj h_head
      obtain ⟨h_xs, h_ys⟩ := ih xs''' h_rest
      exact ⟨by rw [h_x_eq, h_xs], h_ys⟩

/-- A PCP instance `P` is solvable iff the intersection of the two derived context-free grammars
  `topCFG P` and `botCFG P` is non-empty. -/
theorem pcp_iff_nempcfg (P : Stack α) :
    HasSolution P ↔ IntersectionNonempty (topCFG P) (botCFG P) := by
  constructor
  · rintro ⟨A, h_ne, h_mem, h_eq⟩
    refine ⟨canonString Tile.top A, ?_, ?_⟩
    · exact genCFG_generates_canonString Tile.top P A h_ne h_mem
    · have h_canon_eq : canonString Tile.top A = canonString Tile.bot A := by
        simp only [canonString, τProj_top, τProj_bot, h_eq]
      rw [h_canon_eq]
      exact genCFG_generates_canonString Tile.bot P A h_ne h_mem
  · rintro ⟨w, hw_top, hw_bot⟩
    rw [mem_language_iff_canonString] at hw_top hw_bot
    obtain ⟨A_top, h_ne_top, h_mem_top, h_w_top⟩ := hw_top
    obtain ⟨A_bot, _, _, h_w_bot⟩ := hw_bot
    have h_canon : canonString Tile.top A_top = canonString Tile.bot A_bot := by
      rw [← h_w_top, h_w_bot]
    have h_split : (τ1 A_top).map Sum.inl ++ A_top.reverse.map Sum.inr =
                   (τ2 A_bot).map Sum.inl ++ A_bot.reverse.map Sum.inr := by
      simpa only [canonString, τProj_top, τProj_bot] using h_canon
    obtain ⟨h_τ, h_rev⟩ := list_inl_inr_split _ _ _ _ h_split
    have h_A : A_top = A_bot := List.reverse_injective h_rev
    refine ⟨A_top, h_ne_top, h_mem_top, ?_⟩
    rw [h_τ, h_A]

/-- A PCP instance `P` is not solvable iff the intersection of the two derived context-free grammars
  `topCFG P` and `botCFG P` is empty. -/
theorem npcp_iff_empcfg (P : Stack α) :
    ¬ HasSolution P ↔ IntersectionEmpty (topCFG P) (botCFG P) := by
  unfold IntersectionEmpty
  constructor
  · intro h w ⟨hw_top, hw_bot⟩
    exact h ((pcp_iff_nempcfg P).mpr ⟨w, hw_top, hw_bot⟩)
  · intro h h_sol
    obtain ⟨w, hw_top, hw_bot⟩ := (pcp_iff_nempcfg P).mp h_sol
    exact h w ⟨hw_top, hw_bot⟩

end EmpCFG.Reduction
