name = "DiagonaLean"
version = "0.1.0"
defaultTargets = ["DiagonaLean"]
# lintDriver = "batteries/runLinter"

[[lean_lib]]
name = "DiagonaLean"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
