/-
Copyright (c) 2026 Aalok Thakkar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aalok Thakkar
-/

import Mathlib.Computability.ContextFreeGrammar

@[expose] public section

/-! # Empty Intersection of CFGs

Central notions/types and predicates for the CFG intersection-emptiness decision problem.

This is one of the standard problems shown undecidable by reduction from PCP
(see [HopcroftMotwaniUllman2006] Theorem 9.22).

## References

* [J. E. Hopcroft, R. Motwani, J. D. Ullman,
  *Introduction to Automata Theory, Languages, and Computation*][HopcroftMotwaniUllman2006]
-/

namespace DiagonaLean.EmpCFG

open ContextFreeGrammar

variable {T : Type}

/-- `L(G1) ∩ L(G2) = ∅`: no word is generated by both grammars. -/
def IntersectionEmpty (G1 G2 : ContextFreeGrammar T) : Prop :=
  ∀ w : List T, ¬ (w ∈ G1.language ∧ w ∈ G2.language)

/-- `L(G1) ∩ L(G2) ≠ ∅`: some word is generated by both grammars. -/
def IntersectionNonempty (G1 G2 : ContextFreeGrammar T) : Prop :=
  ∃ w : List T, w ∈ G1.language ∧ w ∈ G2.language

/-- `IntersectionEmpty G1 G2` fails iff `IntersectionNonempty G1 G2` holds. -/
lemma not_intersectionEmpty_iff_nonempty (G1 G2 : ContextFreeGrammar T) :
    ¬ IntersectionEmpty G1 G2 ↔ IntersectionNonempty G1 G2 := by
  unfold IntersectionEmpty IntersectionNonempty
  grind

/-- The decision problem of whether the intersection of the languages generated by two context-free grammars is empty. -/
abbrev EmpCFGProblem : ContextFreeGrammar T → ContextFreeGrammar T → Prop := IntersectionEmpty

/-- The decision problem of whether the intersection of the languages generated by a pair of context-free grammars is nonempty. -/
def DecisionProblem (G : ContextFreeGrammar T × ContextFreeGrammar T) : Prop := IntersectionNonempty G.1 G.2

end DiagonaLean.EmpCFG
