/-
Copyright (c) 2026 Aalok Thakkar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aalok Thakkar
-/
module

public import Mathlib.Computability.ContextFreeGrammar

@[expose] public section

/-!
# CFG-Intersection Emptiness

The decision problem **CFG-intersection emptiness** asks: given two
context-free grammars `G1` and `G2`, is `L(G1) ∩ L(G2) = ∅`?

This is one of the standard problems shown undecidable by reduction
from PCP (Hopcroft & Ullman, *Introduction to Automata Theory,
Languages, and Computation*, Theorem 8.10). The reduction is built in
`CFG.PcpReduction`.

This file just states the two decision predicates and a small bridging
lemma. It does **not** prove undecidability — that would require
combining the reduction with a proof of PCP undecidability, which is
not in this repository (see the top-level README).
-/

namespace DiagonaLean.EmpCFG

open ContextFreeGrammar

variable {T : Type}

/-- The decision predicate **"the intersection of `G1` and `G2` is
empty"**: no word is generated by both grammars. -/
def IntersectionEmpty (G1 G2 : ContextFreeGrammar T) : Prop :=
  ∀ w : List T, ¬ (w ∈ G1.language ∧ w ∈ G2.language)

/-- The complementary decision predicate: some word is generated by both
grammars. -/
def IntersectionNonempty (G1 G2 : ContextFreeGrammar T) : Prop :=
  ∃ w : List T, w ∈ G1.language ∧ w ∈ G2.language

lemma not_intersectionEmpty_iff_nonempty
    (G1 G2 : ContextFreeGrammar T) :
    ¬ IntersectionEmpty G1 G2 ↔ IntersectionNonempty G1 G2 := by
  unfold IntersectionEmpty IntersectionNonempty
  grind

abbrev EmpCFG : ContextFreeGrammar T → ContextFreeGrammar T → Prop := IntersectionEmpty

end DiagonaLean.EmpCFG
